resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: rabbitmq
    includeSelectors: true

secretGenerator:
  - name: rabbitmq-secret
    namespace: infra
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
